export const blogs = [
    {
      id: 1,
      title: "Advice From a Software Engineer With 8 Years of Experience",
      author: "Benoit Ruiz",
      date: "Mar 14, 2023",
      readTime: "22 min read",
      views: "18.6K",
      comments: 324,
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NuVWheFUQNItLifZ68pAIw.png",
      content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et risus felis.`,
    },
    {
      id: 2,
      title: "Top 30 JavaScript Interview Questions and Answers for 2025",
      author: "Ravi Sharma",
      date: "Jan 1, 2024",
      readTime: "15 min read",
      views: "2.1K",
      comments: 26,
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NuVWheFUQNItLifZ68pAIw.png",
      content: `This article covers top JavaScript questions with answers to help you crack interviews.`,
    },
    {
      id: 3,
      title: "Top 30 JavaScript Interview Questions and Answers for 2025",
      author: "Ravi Sharma",
      date: "Jan 1, 2024",
      readTime: "15 min read",
      views: "2.1K",
      comments: 26,
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NuVWheFUQNItLifZ68pAIw.png",
      content: `This article covers top JavaScript questions with answers to help you crack interviews.`,
    },
    {
      id: 4,
      title: "Top 30 JavaScript Interview Questions and Answers for 2025",
      author: "Ravi Sharma",
      date: "Jan 1, 2024",
      readTime: "15 min read",
      views: "2.1K",
      comments: 26,
      image: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NuVWheFUQNItLifZ68pAIw.png",
      content: `This article covers top JavaScript questions with answers to help you crack interviews.`,
    },
  ];